name: mirror-falcon-image

on:
  schedule:
    - cron: '3 3 * * *'
  push:
    branches: [ "**" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

jobs:
  login:
    runs-on: ubuntu-latest
    outputs:
      token: ${{ steps.login.outputs.token }}
    steps:
      - name: Get token to login to Amazon ECR
        uses: PhutureCorp/ecr-login-token@v0.8.0
        with:
          registry: 517716713836.dkr.ecr.ap-southeast-1.amazonaws.com
          username: ${{ secrets.ECR_ACCESS_KEY_ID }}
          password: ${{ secrets.ECR_SECRET_ACCESS_KEY }}
      - name: skopeo login to your registry
        run: echo '${{ steps.login_ecr.outputs.token }}' | skopeo login --username  "${{ secrets.YOUR_REGISTRY_USERNAME }}" --password-stdin "${{ secrets.YOUR_REGISTRY }}"
  copy_images:
    runs-on: ubuntu-latest
    needs: login
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Login to Crowdstrike registries and Sync images
        env:
          FALCON_CID: ${{ secrets.FALCON_CID }}
          FALCON_CLIENT_ID: ${{ secrets.FALCON_CLIENT_ID }}
          FALCON_CLIENT_SECRET: ${{ secrets.FALCON_CLIENT_SECRET }}
          FALCON_CLOUD_API: ${{ secrets.FALCON_CLOUD_API }}
          FALCON_CONTAINER_REGISTRY: ${{ secrets.FALCON_CONTAINER_REGISTRY }}
          YOUR_REGISTRY: ${{ secrets.YOUR_REGISTRY }}
          YOUR_REGISTRY_USERNAME: ${{ secrets.YOUR_REGISTRY_USERNAME }}
          YOUR_REGISTRY_PASSWORD: ${{ secrets.YOUR_REGISTRY_PASSWORD }}        
        run: |
          bash ${{ github.workspace }}/falcon-registries-logon-and-sync.sh
