name: mirror-falcon-image

on:
  schedule:
    - cron: '3 3 * * *'
  push:
    branches: [ "**" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

jobs:
  login-to-amazon-ecr:
    permissions:
      contents: read
      packages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID}}:role/${{ secrets.AWS_GITHUB_ROLE_NAME }}
          role-session-name: ${{ secrets.AWS_GITHUB_ROLE_NAME }}
          aws-region: ap-southeast-1
      - name: login-ecr
        uses: aws-actions/amazon-ecr-login@v1  
    outputs:
      registry: ${{ steps.login-ecr.outputs.registry }}
      docker_username: ${{ steps.login-ecr.outputs.docker_username_517716713836_dkr_ecr_ap_southeast_1_amazonaws_com }}
      docker_password: ${{ steps.login-ecr.outputs.docker_password_517716713836_dkr_ecr_ap_southeast_1_amazonaws_com }}
  copy_images:
    runs-on: ubuntu-latest
    needs: login-to-amazon-ecr
    env:
      REGISTRY: ${{ needs.login-to-amazon-ecr.outputs.registry }}
      DOCKER_USERNAME: ${{ needs.login-to-amazon-ecr.outputs.docker_username }}
      DOCKER_PASSWORD: ${{ needs.login-to-amazon-ecr.outputs.docker_password }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: checkoutputs
        run: echo "$DOCKER_PASSWORD" "$DOCKER_USERNAME" "$REGISTRY"
      - name: skopeo login to your registry
        run: echo "$DOCKER_PASSWORD" | skopeo login --username  "$DOCKER_USERNAME" --password-stdin "$REGISTRY"
      - name: Login to Crowdstrike registries and Sync images
        env:
          FALCON_CID: ${{ secrets.FALCON_CID }}
          FALCON_CLIENT_ID: ${{ secrets.FALCON_CLIENT_ID }}
          FALCON_CLIENT_SECRET: ${{ secrets.FALCON_CLIENT_SECRET }}
          FALCON_CLOUD_API: ${{ secrets.FALCON_CLOUD_API }}
          FALCON_CONTAINER_REGISTRY: ${{ secrets.FALCON_CONTAINER_REGISTRY }}
          YOUR_REGISTRY: ${{ secrets.YOUR_REGISTRY }}
          YOUR_REGISTRY_USERNAME: ${{ secrets.YOUR_REGISTRY_USERNAME }}
          YOUR_REGISTRY_PASSWORD: ${{ secrets.YOUR_REGISTRY_PASSWORD }}        
        run: |
          bash ${{ github.workspace }}/falcon-registries-logon-and-sync.sh
